### ISSUE TITLE
Customcommands not working with apps like vi

### ISSUE THREAD

**Issue by windler** [windler/ws#4]
Apps like `vi`or `vim` do not work with CustomCommands, because they need a proper terminal.

Thanks @tylerfowle for adressing this issue.

**Comment by windler** [comment]
@tylerfowle could you try your config with the current `master`?

**Comment by tylerfowle** [comment]
@windler still not working, it just hangs on `ws code ws` 😞

**Comment by windler** [comment]
Strange, I tested it with vi and nvim and it worked after these changes. Whats your OS and Terminal app?

**Comment by tylerfowle** [comment]
@windler using macos 10.12.6 with iTerm2 Build 3.2.0beta6

**Comment by tylerfowle** [comment]
@windler it also hangs in Terminal.app

**Comment by windler** [comment]
@tylerfowle I tried macos + iTerm and it works for me. Are you sure you executed `go get -u github.com/windler/ws`? The `-u` flag is necessary.

**Comment by tylerfowle** [comment]
@windler ah yes, it is working now!

**Comment by windler** [comment]
Great to hear that!
