### ISSUE TITLE
Add the ability to run multiple commands

### ISSUE THREAD

**Issue by tylerfowle** [windler/ws#6]
this might be out of the scope of your project, but to actually be a workspace swiss army knife, you should be able to run multiple commands.  When I start working on a project, I usually want to cd to that directory, maybe checkout a specific branch, open the project in a text editor, start build tools (like gulp or grunt), and open chrome at a certain url

**Comment by windler** [comment]
Sounds reasonable. Except the `cd` that should be possible.
Reading your sample workflow, I think it would be necessary to define custom command "chains" that could be executed in parallel by just one command? E.g. one command would do the following in parallel:
* open workspace in editor
* open browser
* stash/reset changes -> checkout branch -> run build tools

I think the support of "chains" is straight forward to implement. But the yaml structure could be a bit tricky for parallel commands. Also, printig the output of subcommands may get a bit problematic when running commands in parallel (I could think of different colors).

**Comment by tylerfowle** [comment]
i think running the commands in series makes sense.

here is an option of how it could work:
`cmd: "git checkout my_branch && nvim {{.WSRoot}}"`

I know that it is quite different than the current setup.  but this was my initial reaction when trying to compose a custom command.

**Comment by windler** [comment]
yeah, I actually like that way of writing the commands. That will also reduce the size of the responding yaml file.

I think it would also be helpfull to provide custom args so that you can execute something like
```bash
ws switch myrepo master
``` 
while having a config like
```bash
cmd: "git checkout {{index .Args 2}} && nvim {{.WSRoot}}"
```
`{{index .Args 0}}` would then be evaluated to `switch` and `{{index .Args 1}}` to `myrepo`.

I will start/think of an implemenatation within the next days. You can contribute to the implementation if you like.

**Comment by windler** [comment]
In config yaml, the `Args` key is removed and now you have to write your commands like
```bash
cmd: "git checkout my_branch && nvim {{.WSRoot}}"
```

Also, you can now get the commands Args via 
```bash
{{.Args}}
```
